### ISSUE TITLE
The printf problem

### ISSUE THREAD

**Issue by juxin-niu** [Yuano0o/alpaca#2]
关于工程无法正常使用printf输出，问题出在如下的代码中。

https://github.com/Yuano0o/alpaca/blob/242b641409e614603e9a7dd3526d4d2a78862269/JustInTime_vs_Periodic/driver/uart2target.h#L14-L31

在程序对UART的初始化时，会为UART分配一个TX口，即上面代码看到的那样。以MSP430FR5994来说，在代码中，程序对eUSI_A3进行初始化，并分配TX端口Port6.0。

**以MSP430FR5994来说，其开发板的引脚图分布可以在网站 https://www.ti.com/lit/ug/slau678b/slau678b.pdf?ts=1667952627555 上查阅得到。Port6.0，也就是该程序为UART分类的端口上图中看到。显然，在这里分配的TX口并不是从MSP430开发板到主机上的，因此数据也就不会被正确地发送到主机上。**

![image](https://user-images.githubusercontent.com/88332544/200844307-1e8b7f92-2123-4bd5-8a75-823176a3a70f.png)

一般来说，有两种方式可以解决这个问题，修改上面脚本的UART端口，或者使用杜邦线将到主机的Host进行重定向。对于这个问题，第一种方式是推荐的。在 https://www.ti.com/lit/ug/slau678b/slau678b.pdf?ts=1667952627555 的2.2.4部分，可以看到MSP430FR5994的与Host的连接是eUSCI_A0，对应于代码，应该是

```c
     #define UART_TX_PORT            GPIO_PORT_P2 /* Modified */
     #define UART_TX_PIN             GPIO_PIN0 
     #define UART_TX_FUNCTION        GPIO_PRIMARY_MODULE_FUNCTION 
     #define UART_BASEADDR           EUSCI_A0_BASE  /*Modified*/
```

> 这些数据可能有错误，并且因开发板的不同而异。
> 
> 开发板包括芯片，通过在Google上搜索`MSP430FRxxxx` 可以获得关于芯片的User Guide（包括各个功能模块的使用）和Data sheet（各个功能模块的具体参数和引脚分布）。
>
> 通过在Google上搜索`MSP430FRxxxx Development kit`可以获得关于开发板的User Guide（包括调试功能、Boostpack等）。

**Comment by Yuano0o** [comment]
UART_TX_PORT和UART_BASEADDR改成P2和EUSCI_A0_BASE了 但printf还是没有显示.
而且我移植ink的UART_initGPIO和UART_init后,在这个工程上也不起作用 
是不是有其他问题?
