### ISSUE TITLE
printf还是没有显示

### ISSUE THREAD

**Issue by Yuano0o** [Yuano0o/alpaca#3]
UART_TX_PORT和UART_BASEADDR改成P2和EUSCI_A0_BASE了 但printf还是没有显示.
而且我移植ink的UART_initGPIO和UART_init后,在这个工程上也不起作用 
是不是有其他问题?

_Originally posted by @Yuano0o in https://github.com/Yuano0o/alpaca/issues/2#issuecomment-1309795303_

**Comment by juxin-niu** [comment]
我晚些时候检查一下代码。

在这之前，可以先在程序中设置断点，做简单的验证和时间测量。不要被这个问题影响进度。

**Comment by Yuano0o** [comment]
我取消了重定向,可以在console输出.

**Comment by juxin-niu** [comment]
目前这样可行。但是如果后续需要断电，或者进行更为复杂的测量，则这种方法会有问题。

这个问题可以后续解决。
