### ISSUE TITLE
pc_ar.c  war数组未备份

### ISSUE THREAD

**Issue by Yuano0o** [Yuano0o/alpaca#4]
_v_window在ar的task3中是war数组.
<img width="679" alt="image" src="https://user-images.githubusercontent.com/105616449/201095693-33687fbf-5c55-497e-be9a-d3eb5c20915a.png">

但没有被备份.将在下面两处修改.
![image](https://user-images.githubusercontent.com/105616449/201095866-8ebd7009-e433-4167-ad61-c9aac63836d8.png)

**Comment by juxin-niu** [comment]
如果使用Latics的分析方法，`_v_window`的确**是WAR数组**。但是如果进行更为精细的分析，可以发现该数组的读写**不会引发任何WAR依赖**。

**在这里，将其看作WAR数组即可**。

**Comment by Yuano0o** [comment]
`dafg`
